Student ID:202318051
Name: Vansh Shah

**Task A:**
###Develop Python code to perform block multiplication on two given matrices.

In [277]:
import numpy as np
# Declaring Matrices M1 and M2
M1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
M2= np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

#Getting the shape value and dividing it by 2
print("Matrix M1:")
print(M1)
print("\nMatrix M2:")
print(M2)

print(M1.shape)
n = M1.shape[0] // 2
# Populating the values of matrices, each matrice divided into 4 submatrice

MUL = M1[:n, :n]
MUR = M1[:n, n:]
MLL = M1[n:, :n]
MLR = M1[n:, n:]

PUL = M2[:n, :n]
PUR = M2[:n, n:]
PLL = M2[n:, :n]
PLR = M2[n:, n:]

# Calculating the product of sub matrixj

UL = np.dot(MUL, PUL) + np.dot(MUR, PLL)
UR = np.dot(MUL, PUR) + np.dot(MUR, PLR)
LL = np.dot(MLL, PUL) + np.dot(MLR, PLL)
LR = np.dot(MLL, PUR) + np.dot(MLR, PLR)
# Combining the matrices
M=np.vstack([np.hstack([UL, LL]), np.hstack([UR, LR])])

print(M)

Matrix M1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix M2:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
(4, 4)
[[ 80  70 400 358]
 [240 214 560 502]
 [ 60  50 316 274]
 [188 162 444 386]]


**Task B:**
###This segment of the assignment is designed to enhance your understanding of the API call process and dataset creation. Utilize any freely available API endpoint on Rapidapi to generate a dataset.

In [278]:
#importing necessary libraries

import requests
import pandas as pd
import time

url = "https://realtor.p.rapidapi.com/locations/v2/auto-complete"

headers = {
    "X-RapidAPI-Key": "1b35b22ac2msh688c20214fbf895p1b5d6bjsn4d5a74f65ba9",
    "X-RapidAPI-Host": "realtor.p.rapidapi.com",
}

# Number of entries we want in our data set
entry_count = 200

# This list will store all the entries which are fetched
all_entries = []


while len(all_entries) < entry_count:
    querystring = {"input": "new york", "limit": "10"}
    response = requests.get(url, headers=headers, params=querystring)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()

        # Appending the results to the list
        all_entries.extend(data['autocomplete'])

        # Update the querystring to get the next set of entries
        querystring['offset'] = len(all_entries)

        # As the API im using has a limit of 5 reqest per second im limiting the number
        # of calls program make to 0.2 per second
        time.sleep(0.2)
    else:
        print(f"Error: {response.status_code}")
        break  # Exit the loop on error

In [279]:
# Create a DataFrame from the collected entries
df = pd.DataFrame(all_entries)

# Optionally, save the DataFrame to a CSV file
df.to_csv("real_estate_dataset.csv", index=False)

display(df)

area_type                     _id        _score     state state_code  \
0       state                state:ny  36035.560000  New York         NY   
1        city        city:ny_new-york     34.656440       NaN         NY   
2        city       city:ny_manhattan     34.545000       NaN         NY   
3        city  city:ny_new-york-mills     33.838245       NaN         NY   
4        city  city:mn_new-york-mills     33.807926       NaN         MN   
..        ...                     ...           ...       ...        ...   
195    school       school:0751622721     33.630510       NaN         NY   
196    school       school:0751685001     33.508330       NaN         NY   
197    school       school:0751470731     33.392864       NaN         NY   
198    county      county:ny_new-york     33.358700       NaN         NY   
199    school       school:0751470741     33.328373       NaN         NY   

    country                                           centroid  \
0       USA  {'lon': -75.5965453188093, 'lat': 42.921242156...   
1       USA            {'lon': -73.9386968, 'lat': 40.6634682}   
2       USA            {'lon': -73.9701871, 'lat': 40.7766419}   
3       USA            {'lon': -75.2931141, 'lat': 43.1007037}   
4       USA            {'lon': -95.3727804, 'lat': 46.5196303}   
..      ...                                                ...   
195     USA              {'lon': -73.995705, 'lat': 40.741074}   
196     USA              {'lon': -78.184921, 'lat': 43.006557}   
197     USA              {'lon': -75.291348, 'lat': 43.092457}   
198     USA            {'lon': -73.9701871, 'lat': 40.7766419}   
199     USA              {'lon': -75.291134, 'lat': 43.092351}   

                                               slug_id  \
0                                             New-York   
1                                          New-York_NY   
2                                         Manhattan_NY   
3                                    New-York-Mills_NY   
4                                    New-York-Mills_MN   
..                                                 ...   
195                         New-York-Hebrew-0751622721   
196     New-York-State-School-For-The-Blind-0751685001   
197        New-York-Mills-Elementary-School-0751470731   
198                                 New-York-County_NY   
199  New-York-Mills-Junior-Senior-High-School-07514...   

                                   geo_id            city  \
0    7a9bffcb-e43c-5cdd-89ff-08ead6d8225d             NaN   
1    a5cac742-26a8-5870-b961-472ec6f9d824        New York   
2    e87a8b91-b532-5d20-a050-0551631a2c79       Manhattan   
3    45f53d11-3a2c-5b81-8fed-7dd7f735ccd9  New York Mills   
4    559960d6-8da6-5e37-a7cf-3859260b51e3  New York Mills   
..                                    ...             ...   
195                                   NaN        New York   
196                                   NaN         Batavia   
197                                   NaN  New York Mills   
198  227f1784-883d-552e-bc7b-944ee20e681b             NaN   
199                                   NaN  New York Mills   

                                              counties county_needed_for_uniq  \
0                                                  NaN                    NaN   
1    [{'name': 'Queens', 'fips': '36081', 'state_co...                  False   
2    [{'name': 'New York', 'fips': '36061', 'state_...                  False   
3    [{'name': 'Oneida', 'fips': '36065', 'state_co...                  False   
4    [{'name': 'Otter Tail', 'fips': '27111', 'stat...                  False   
..                                                 ...                    ...   
195                                                NaN                    NaN   
196                                                NaN                    NaN   
197                                                NaN                    NaN   
198                                                NaN    

**Task C:**
### In this part of the assignment, you will learn how to construct a dataset by scraping a website online. Utilize BeautifulSoup or any other suitable scraping library to extract all the details of Amazon products and compile a dataset.

In [280]:
#importing beautifulsoup
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = 'https://www.amazon.in/s?k=smartphones&crid=3PSD4Z9BPQ0TE&sprefix=smartphone%2Caps%2C300&ref=nb_sb_noss_1'

response = requests.get(url)

custom_headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
    'accept-language': 'en-GB,en;q=0.9',
}

In [281]:
#function checks the response status, acts accordingly and scraps the data mentioned
def get_product_info(url):
    response = requests.get(url, headers=custom_headers)
    if response.status_code != 200:
        print("Error in getting webpage")
        exit(-1)

    soup = BeautifulSoup(response.text, "lxml")

    title_ele = soup.select_one("#productTitle")
    title = title_ele.text.strip() if title_ele else None

    price_ele = soup.select_one("#price_inside_buybox")
    price = price_ele.text if price_ele else None

    rating_ele = soup.select_one("#acrPopover")
    rating_text = rating_ele.attrs.get("title") if rating_ele else None
    rating = rating_text.replace("out of 5 stars", "") if rating_text else None

    image_ele = soup.select_one("#landingImage")
    image = image_ele.attrs.get("src") if image_ele else None

    desc_ele = soup.select_one("#productDescription")
    description = desc_ele.text.strip() if desc_ele else None

    return {
        "title": title,
        "price": price,
        "rating": rating,
        "image": image,
        "description": description,
        "url": url
    }

def parse_listing(listing_url, page_limit=3, current_page=1):
    response = requests.get(listing_url, headers=custom_headers)
    print(response.status_code)
    soup_search = BeautifulSoup(response.text, "lxml")
    link_elements = soup_search.select("[data-asin] h2 a")
    page_data = []

    for link in link_elements:
        full_url = urljoin(listing_url, link.attrs.get("href"))
        print(f"Scraping product from {full_url[:100]}", flush=True)
        product_info = get_product_info(full_url)
        page_data.append(product_info)

    next_page_el = soup_search.select_one('a:contains("Next")')

    if next_page_el and current_page < page_limit:
        next_page_url = next_page_el.attrs.get('href')
        next_page_url = urljoin(listing_url, next_page_url)
        print(f'Scraping next page: {next_page_url}', flush=True)
        page_data += parse_listing(next_page_url, page_limit=page_limit, current_page=current_page + 1)

    return page_data

def main():
    data = []
    search_url = "https://www.amazon.in/s?k=smartphones&crid=3PSD4Z9BPQ0TE&sprefix=smartphone%2Caps%2C300&ref=nb_sb_noss_1"
    data = parse_listing(search_url, page_limit=3)
    df = pd.DataFrame(data)
    df.to_json("amz.json", orient='records')

if __name__ == '__main__':
    main()


200
Scraping product from https://www.amazon.in/realme-Feather-Segment-Charging-Slimmest/dp/B0CKN56PQ8/ref=sr_1_1?crid=3PSD4Z9
Scraping product from https://www.amazon.in/realme-Feather-Segment-Charging-Slimmest/dp/B0C45VWDWJ/ref=sr_1_2?crid=3PSD4Z9
Scraping product from https://www.amazon.in/Stardust-Storage-Powered-MediaTek-Display/dp/B0CMTWQYFM/ref=sr_1_3?crid=3PSD4Z
Scraping product from https://www.amazon.in/Starfrost-Storage-Powered-MediaTek-Display/dp/B0CMTY5P4V/ref=sr_1_4?crid=3PSD4
Scraping product from https://www.amazon.in/Samsung-Midnight-sAMOLED-Display-Security/dp/B0C7BZX934/ref=sr_1_5?crid=3PSD4Z
Scraping product from https://www.amazon.in/Redmi-Sea-Green-64GB-Storage/dp/B0C74PD9VG/ref=sr_1_6?crid=3PSD4Z9BPQ0TE&keywo
Scraping product from https://www.amazon.in/Samsung-Midnight-Storage-6000mAh-Battery/dp/B0B4F52B5X/ref=sr_1_7?crid=3PSD4Z9
Scraping product from https://www.amazon.in/Starshine-Storage-Powered-MediaTek-Display/dp/B0CMTWJ5RV/ref=sr_1_8?crid=3PSD4
Scraping pro

In [282]:
df = pd.read_json('/content/amz.json')
df.to_csv('amazon_products.csv', encoding='utf-8', index=False)
display(df)

title  price  rating  \
0   realme narzo N53 (Feather Black, 8GB+128GB) 33...    NaN     4.0   
1   realme narzo N53 (Feather Black, 4GB+64GB) 33W...    NaN     4.0   
2   Redmi 13C (Stardust Black, 8GB RAM, 256GB Stor...    NaN     4.0   
3   Redmi 13C (Starfrost White, 4GB RAM, 128GB Sto...    NaN     4.0   
4   Samsung Galaxy M34 5G (Midnight Blue,6GB,128GB...    NaN     4.0   
5         Redmi A2 (Sea Green, 2GB RAM, 64GB Storage)    NaN     3.9   
6   Samsung Galaxy M13 (Midnight Blue, 4GB, 64GB S...    NaN     4.1   
7   Redmi 13C (Starshine Green, 6GB RAM, 128GB Sto...    NaN     4.0   
8   OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...    NaN     4.2   
9   Xiaomi Redmi 10 Power (Power Black, 8GB RAM, 1...    NaN     4.0   
10  Samsung Galaxy M13 (Aqua Green, 4GB, 64GB Stor...    NaN     4.1   
11  Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...    NaN     3.8   
12  Samsung Galaxy M04 Dark Blue, 4GB RAM, 128GB S...    NaN     3.9   
13        Redmi A2 (Aqua Blue, 2GB RAM, 64GB Storage)    NaN     3.9   
14  Samsung Galaxy M04 Light Green, 4GB RAM, 128GB...    NaN     3.9   
15    Redmi A2 (Classic Black, 2GB RAM, 64GB Storage)    NaN     3.9   
16  TECNO POP 8 (Mystery White,(8GB*+64GB)|90Hz Pu...    NaN     4.4   
17  realme narzo N53 (Feather Black, 8GB+128GB) 33...    NaN     4.0   
18  realme narzo N53 (Feather Black, 4GB+64GB) 33W...    NaN     4.0   
19  Redmi 13C (Stardust Black, 8GB RAM, 256GB Stor...    NaN     4.0   
20  Redmi 13C (Starfrost White, 4GB RAM, 128GB Sto...    NaN     4.0   
21  Samsung Galaxy M34 5G (Midnight Blue,6GB,128GB...    NaN     4.0   
22        Redmi A2 (Sea Green, 2GB RAM, 64GB Storage)    NaN     3.9   
23  Samsung Galaxy M13 (Midnight Blue, 4GB, 64GB S...    NaN     4.1   
24  Redmi 13C (Starshine Green, 6GB RAM, 128GB Sto...    NaN     4.0   
25  OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...    NaN     4.2   
26  Xiaomi Redmi 10 Power (Power Black, 8GB RAM, 1...    NaN     4.0   
27  Samsung Galaxy M13 (Aqua Green, 4GB, 64GB Stor...    NaN     4.1   
28  Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...    NaN     3.8   
29  Samsung Galaxy M04 Dark Blue, 4GB RAM, 128GB S...    NaN     3.9   
30        Redmi A2 (Aqua Blue, 2GB RAM, 64GB Storage)    NaN     3.9   
31  Samsung Galaxy M04 Light Green, 4GB RAM, 128GB...    NaN     3.9   
32    Redmi A2 (Classic Black, 2GB RAM, 64GB Storage)    NaN     3.9   
33  TECNO POP 8 (Mystery White,(8GB*+64GB)|90Hz Pu...    NaN     4.4   
34  realme narzo N53 (Feather Black, 8GB+128GB) 33...    NaN     4.0   
35  realme narzo N53 (Feather Black, 4GB+64GB) 33W...    NaN     4.0   
36  Redmi 13C (Stardust Black, 8GB RAM, 256GB Stor...    NaN     4.0   
37  TECNO POP 8 (Mystery White,(8GB*+64GB)|90Hz Pu...    NaN     4.4   
38  Redmi 13C (Starfrost White, 4GB RAM, 128GB Sto...    NaN     4.0   
39  Samsung Galaxy M34 5G (Midnight Blue,6GB,128GB...    NaN     4.0   
40        Redmi A2 (Sea Green, 2GB RAM, 64GB Storage)    NaN     3.9   
41  Samsung Galaxy M13 (Midnight Blue, 4GB, 64GB S...    NaN     4.1   
42  Redmi 13C (Starshine Green, 6GB RAM, 128GB Sto...    NaN     4.0   
43  OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...    NaN     4.2   
44  Xiaomi Redmi 10 Power (Power Black, 8GB RAM, 1...    NaN     4.0   
45  Samsung Galaxy M13 (Aqua Green, 4GB, 64GB Stor...    NaN     4.1   
46  Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...    NaN     3.8   
47  Samsung Galaxy M04 Dark Blue, 4GB RAM, 128GB S...    NaN     3.9   
48        Redmi A2 (Aqua Blue, 2GB RAM, 64GB Storage)    NaN     3.9   
49  Samsung Galaxy M04 Light Green, 4GB RAM, 128GB...    NaN     3.9   
50    Redmi A2 (Classic Black, 2GB RAM, 64GB Storage)    NaN     3.9   

                                                image  description  \
0   https://m.media-amazon.com/images/I/41QssaE9gf...          NaN   
1   https://m.media-amazon.com/images/I/41QssaE9gf...          NaN   
2   https://m.media-amazon.com/images/I/412bETihpN...          NaN   
3   https://m.media-ama